[package]
name = "learning_action"
version = "0.0.1"
authors = ["cds <chengdongsheng@outlook.com>"]
edition = "2021"

[[bin]]
name = "action_move_server"
path = "src/action_move_server.rs"

[[bin]]
name = "action_move_client"
path = "src/action_move_client.rs"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
futures = "0.3"
rclrs = "*"

# This specific version is compatible with Rust 1.75
backtrace = "=0.3.74"
learning_interface = "*"

# uncomment the following section in order to fill in
# further dependencies manually.
# <dependency> = "*" 
