[package]
name = "learning_topic_rs"
version = "0.0.1"
authors = ["cds <chengdongsheng@outlook.com>"]
edition = "2021"

[[bin]]
name = "node_sub"
path = "src/node_sub.rs"

[[bin]]
name = "node_pub"
path = "src/node_pub.rs"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
rclrs = "*"
std_msgs = "*"

# This specific version is compatible with Rust 1.75
backtrace = "=0.3.74"

# uncomment the following section in order to fill in
# further dependencies manually.
# <dependency> = "*" 
