[package]
name = "learning_service_rs"
version = "0.0.1"
authors = ["cds <chengdongsheng@outlook.com>"]
edition = "2021"

[[bin]]
name = "adder_server"
path = "src/adder_server.rs"

[[bin]]
name = "adder_client"
path = "src/adder_client.rs"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
rclrs = "*"

# This specific version is compatible with Rust 1.75
backtrace = "=0.3.74"

learning_interface = "*"

# uncomment the following section in order to fill in
# further dependencies manually.
# <dependency> = "*" 
